spring:
  application:
    name: collaborationTool
  profiles:
    active: prod
  session:
    jdbc:
      initialize-schema: always

server:
  address: 0.0.0.0
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json
    min-response-size: 1024

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  redis:
    token-prefix: revoked_token
  message: "This is the default message"

logging:
  file:
    name: logs/backend.log
    path: logs
  level:
    root: INFO
    level.com.eclectics.collaboration: DEBUG

jwt:
  secret: ${JWT_SECRET}
