spring:
  mail:
    host: ${MAIL_TRAP_HOST}
    port: ${MAIL_TRAP_PORT}
    username: ${MAIL_TRAP_USERID}
    password: ${MAIL_TRAP_PASSWORD}
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/collaborationTool
    username: prod_admin
    password: ${PROD_DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

server:
  port: 8084

alibaba:
  cloud:
    oss:
      endpoint: https://oss-eu-west-1.aliyuncs.com
      access-key-id: ${OSS_KEY}
      access-key-secret: ${OSS_SECRET}
      bucket-name: jagarage

app:
  message: "This is the Production environment"

jwt:
  secret: ${JWT_SECRET}